### ISSUE TITLE
Authorizing app issue

### ISSUE THREAD

**Issue by yabirgb** [jamiesanson/Mammut#2] opened 2018-11-18 19:11 UTC
After installing the version on the play store when I logging in the app and authorize it I get a 'Oh jeez, something went wrong' message

**Comment by jamiesanson** [comment] 2018-11-20 19:38
Hi @yabirgb 

Were you able to get a stacktrace of the error when this occurred? I'll add more extensive logging around this area to see if I can see it on my end.

**Comment by yabirgb** [comment] 2018-11-20 20:06
Nope, what a I did was:

1. Search my instance
2. A browser tap opens
3. I enter my credentials
4. Click on authorize
5. Back to the app I get that error

**Comment by jamiesanson** [comment] 2018-11-20 21:57
Ah yes. I've seen this before, but have yet been able to reproduce it. I'll add more logging in this area in the next alpha release and see if we can get to the bottom of it. Thanks for the bug report! I'll keep you posted.

**Comment by jamiesanson** [comment] 2018-12-22 08:29
Looks like the issue is to do with browser caching. I've added custom tabs for OAuth and plan on releasing the fix for this shortly!

**Closed as completed by jamiesanson** 2018-12-22 08:29 UTC
